{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stampbot.fullname" . }}-external
  labels:
    {{- include "stampbot.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  target:
    name: {{ include "stampbot.fullname" . }}-external
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- if .remoteRef.property }}
      property: {{ .remoteRef.property }}
      {{- end }}
  {{- end }}
{{- end }}
