{{- if and (not .Values.github.existingSecret) (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stampbot.fullname" . }}
  labels:
    {{- include "stampbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  STAMPBOT_APP_ID: {{ .Values.github.appId | quote }}
  STAMPBOT_PRIVATE_KEY: {{ .Values.github.privateKey | quote }}
  STAMPBOT_WEBHOOK_SECRET: {{ .Values.github.webhookSecret | quote }}
{{- end }}
